### ISSUE TITLE
update for latest APIs

### ISSUE THREAD

**Issue by ripienaar** [JoshVanL/cert-managerctl#1]
I like the idea of a CLI to the cert manager but noticed this one is using ancient APIs, is this still maintained? Or do you perhaps know of a newer tool that fills the same need?

**Comment by JoshVanL** [comment]
Hi @ripienaar :) 

This is an old experiment I did around creating a CLI. The [latest release](https://github.com/jetstack/cert-manager/releases/tag/v0.15.0) includes a new CLI which is compatible as a kubectl plugin, which includes conversion and manual renewal (with the newer controllers behind feature gates). There is also a [PR being worked on](https://github.com/jetstack/cert-manager/pull/2957) for creating CertificateRequests.

What are the things that you are looking from the CLI? We'd be keen to hear real world use cases for shaping what functionality we should be including. An issue over on [cert-manager](https://github.com/jetstack/cert-manager/issues/new/choose) would be greatly appreciated.

**Comment by ripienaar** [comment]
main thing for my need is to submit a CSR and get back the cert :) I'll use the API was just being lazy tbh

**Comment by JoshVanL** [comment]
Sounds good, the above PR should be be helpful here when it's ready^
